on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Bazel test
    steps:
      - uses: actions/checkout@v2
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel test //src/...
